## For this assignment we will write a dynamic program that will return the longest common substring between two strings. Dynamic programming helps us optimize the process that without dynamic programming, would lead to a much less efficient time complexity, because we would have to esentially find all of the substrings within each string and find the longest that is found in both. We can get these results in a more efficent manner in a dynamic way.

In [1]:
import numpy as np

In [110]:
def lcs(x, y, m, n):
    L = [[0 for x in range(n+1)] for x in range(m+1)]
  
    #L acts as our matrix for our string characters

    for i in range(m+1):
        for j in range(n+1):
            if i == 0 or j == 0:
                L[i][j] = 0
            elif x[i-1] == y[j-1]:
                L[i][j] = L[i-1][j-1] + 1
            else:
                L[i][j] = max(L[i-1][j], L[i][j-1])
  
    # Above we are iterating with i and j over the ranges+1 of the lengths of our strings
    # and setting wherever i or j == 0 to 0 in our L matrix (where empty string is located).
    # If this condition is not met, we see if the index of i-1 in X is equal to the index of 
    # j-1 in Y (comparing string characters at specific locations). If this condition is met, 
    # we set L at index i by j equal to its diagonal + 1. If neither of these are met, we set 
    # L of index i by j to the max of either cell i-1 (upper) or j-1 (left)
    
    print(np.array(L))
    index = L[m][n]
    print("The LCS length is " + str(index))
    
    #index gives us the bottom right most cell value (the LCS length)
    
    LCS = [""] * (index+1)
    
    
    # Create our lcs as an empty string, and multiply it by our bottom right most cell value 
    # to create an empty string for each character in our LCS
    
    
    # Start from the right-most-bottom-most corner and
    # one by one store characters in lcs[]
    i = m
    j = n
    while i > 0 and j > 0:
        
    # We now set our index markers i and j to the bottom right most cell to begin back tracking 
    # and adding our characters found in both strings. We use a while loop to continue the following 
    # process until both of our indecies have reached 0 and the entire matrix has been spanned
  
        # If current character in X[] and Y are same, then
        # current character is part of LCS
        if x[i-1] == y[j-1]:
            LCS[index-1] = x[i-1]
            i-=1
            j-=1
            index-=1
            
        #If the given character in our X string and Y string are the same, then the current character 
        # is part of the LCS, and the right most index in our list of empty strings (lcs) is set equal 
        # to that character from the X string, and our i and j indecies both decrease by one to move 
        # to the left diagonal where we now know we can from. Our index value also reduces to add 
        # the next potential character
  
        # If not same, then find the larger of two and
        # go in the direction of larger value
        elif L[i-1][j] > L[i][j-1]:
            i-=1
        else:
            j-=1
            
        #If the given characters from index i in string X and index j in string Y are not the same, 
        # then we find whichever cell value was larger, and move our indecies to that cell to continue 
        # the appropriate backtracking route
  
    print("LCS of " + x + " and " + y + " is " + "".join(LCS))
    
#Last, we print our X string, Y string, and use the join function to return all of the individual 
#string values into one string, thus printing our LCS

In [111]:
x = "HORSEBACK"
y = "SNOWFLAKE"
m = len(x)
n = len(y)
lcs(x, y, m, n)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 1 1 1 1 1]
 [0 0 0 1 1 1 1 1 1 1]
 [0 1 1 1 1 1 1 1 1 1]
 [0 1 1 1 1 1 1 1 1 2]
 [0 1 1 1 1 1 1 1 1 2]
 [0 1 1 1 1 1 1 2 2 2]
 [0 1 1 1 1 1 1 2 2 2]
 [0 1 1 1 1 1 1 2 3 3]]
The LCS length is 3
LCS of HORSEBACK and SNOWFLAKE is SAK
